name = "blogverse"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

[vars]

[[d1_databases]]
binding = "DB"
database_name = "blogverse_db"
database_id = "5a62553c-e713-4047-9dd9-4764866754be"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "blogverse-assets"

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "blogverse_events"